"use client";
import {useMemo,useState} from "react";
import {Search,TrendingUp,Package,ShoppingCart,Bookmark,SlidersHorizontal,ArrowUpRight} from "lucide-react";
const products=[
{id:1,title:"LED Halloween Pumpkin Lights",category:"Halloween",price:24.99,sold:183,active:27,trend:82,supplier:6.82,season:"Halloween"},
{id:2,title:"Pet Hair Remover Roller",category:"Pet Supplies",price:18.99,sold:421,active:64,trend:76,supplier:4.91,season:"Evergreen"},
{id:3,title:"Christmas Window Projector",category:"Christmas",price:34.99,sold:118,active:19,trend:88,supplier:9.75,season:"Christmas"},
{id:4,title:"Foldable Car Storage Organizer",category:"Automotive",price:29.99,sold:267,active:43,trend:64,supplier:8.20,season:"Evergreen"},
{id:5,title:"Autumn Leaf Garland",category:"Fall",price:21.99,sold:96,active:14,trend:71,supplier:5.60,season:"Fall"}];
export default function Home(){const[q,setQ]=useState("");const[country,setCountry]=useState("US");const[season,setSeason]=useState("All");const[view,setView]=useState("hunter");const filtered=useMemo(()=>products.filter(p=>(!q||p.title.toLowerCase().includes(q.toLowerCase())||p.category.toLowerCase().includes(q.toLowerCase()))&&(season==="All"||p.season===season)),[q,season]);return <main><aside><div className="brand"><div className="logo">PH</div><div><b>Product Hunter</b><span>eBay Intelligence</span></div></div><nav>{["hunter","trending","seasonal","saved"].map((x)=><button className={view===x?"active":""} onClick={()=>setView(x)} key={x}>{x==="hunter"?<Search/>:x==="trending"?<TrendingUp/>:x==="seasonal"?<Package/>:<Bookmark/>}{x[0].toUpperCase()+x.slice(1)}</button>)}</nav><div className="sidebox"><small>MARKET</small><select value={country} onChange={e=>setCountry(e.target.value)}><option>US</option><option>UK</option><option>CA</option><option>AU</option><option>DE</option></select></div></aside><section className="content"><header><div><p className="eyebrow">MARKET: {country}</p><h1>{view==="hunter"?"Find winning eBay products":"Product Intelligence"}</h1><p className="muted">Research demand, competition, trends and sourcing in one place.</p></div><button className="primary"><ShoppingCart/> Connect data</button></header><div className="stats"><div><TrendingUp/><span>Trending Products</span><strong>1,284</strong></div><div><ShoppingCart/><span>Products Sold</span><strong>42.8K</strong></div><div><Package/><span>Avg. Sell-through</span><strong>68.4%</strong></div><div><ArrowUpRight/><span>Rising Opportunities</span><strong>317</strong></div></div><div className="toolbar"><div className="search"><Search/><input placeholder="Search products, keywords or categories..." value={q} onChange={e=>setQ(e.target.value)}/></div><select value={season} onChange={e=>setSeason(e.target.value)}><option>All</option><option>Halloween</option><option>Christmas</option><option>Fall</option><option>Evergreen</option></select><button className="filter"><SlidersHorizontal/> Filters</button></div><div className="sectionhead"><div><h2>Product opportunities</h2><p>{filtered.length} matching products</p></div><select><option>Sort: Opportunity</option><option>Sales</option><option>Trend</option><option>Price</option></select></div><div className="table"><div className="thead"><span>PRODUCT</span><span>EBAY PRICE</span><span>SOLD</span><span>ACTIVE</span><span>TREND</span><span>SUPPLIER</span><span></span></div>{filtered.map(p=><div className="row" key={p.id}><div className="product"><div className="thumb">{p.category.slice(0,2).toUpperCase()}</div><div><b>{p.title}</b><small>{p.category} · {p.season}</small></div></div><strong>${p.price.toFixed(2)}</strong><span>{p.sold}</span><span>{p.active}</span><span className="trend">↑ {p.trend}%</span><span>${p.supplier.toFixed(2)}</span><button className="icon"><Bookmark size={17}/></button></div>)}</div></section></main>}